# Generated by Django 2.0.2 on 2018-03-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_comment',
            new_name='author',
        ),
    ]
