# Generated by Django 2.0.2 on 2018-03-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20180314_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-rating']},
        ),
    ]
