# Generated by Django 2.0.2 on 2018-03-13 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_avatar', models.ImageField(default='profile_avatar/default.png', upload_to='profile_avatar/')),
                ('birthday', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
