# Generated by Django 2.0.2 on 2018-03-13 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='boards',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='boards.Board'),
        ),
    ]
