# Generated by Django 2.0.2 on 2018-03-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='comment_pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cardsonlist',
            name='card_time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='list_time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
