# Generated by Django 2.0.2 on 2018-03-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20180313_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='command',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='last_change_board',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='comment_text',
            field=models.TextField(max_length=2000),
        ),
    ]
